### ISSUE TITLE
Check if Password is Set

### ISSUE THREAD

**Issue by Mobmaker55** [sourque/aeacus#102]
For users without any password, how would you check if one was applied for Windows?
I tried using `PasswordChanged` with `arg2=' '` and that didn't work for me, are there any other ways to do this?

**Comment by Akshay-Rohatgi** [comment]
Password Changed is kind of broken right now, we're working on a fix.

**Comment by Akshay-Rohatgi** [comment]
Alright, the Windows PasswordChanged check is fixed, here is the documentation on how to use the check.

![image](https://user-images.githubusercontent.com/52616034/113491998-a8e5e080-9489-11eb-88cf-d287063b321e.png)

**Comment by Mobmaker55** [comment]
So, I still can't get the Windows PasswordChanged check to work right. No matter what, it gives points.

**Comment by Akshay-Rohatgi** [comment]
can you send a screenshot or snippet of your config

**Comment by Mobmaker55** [comment]
![image](https://user-images.githubusercontent.com/45888585/114481636-f1f90b80-9bd2-11eb-9bd9-a4ab7664d206.png)
This is the check for changing the password.

**Comment by Akshay-Rohatgi** [comment]
can you try changing the `4` in arg2 to `04`, so it would be `04/12/2021`

**Comment by Mobmaker55** [comment]
It still just gave me the points.
